development:
  secret_key_base: 18aebf341f987fe5707533f39ac1db2dd44ff52aad3b46fe23681e9c168fa628ffb4aaa3e202436f5feec5e2726f601994ca2e0280ce9ca561246ab26794c889
  SECRET_HMAC: f093034407b80bd12e09c16194198a3923824262
  SMTP_ADDRESS: <%= ENV["SMTP_ADDRESS"] %>
  SMTP_USER_NAME: <%= ENV["SMTP_USER_NAME"] %>
  SMTP_PASSWORD: <%= ENV["SMTP_PASSWORD"] %>
  SMTP_DOMAIN: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_FROM: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_ERRORS_RECEIVER: <%= ENV["EMAIL_ERRORS_RECEIVER"] %>

test:
  secret_key_base: 526d009f4c2b2b6c7d6a21a855f64c8847b19db4ab2b43be094d99b12289212124dae046e47a72bf0c38dea60345e8c6125ec1542ad1042448ebbe5239e4a78c
  SECRET_HMAC: f093034407b80bd12e09c16194198a3923824262
  SMTP_ADDRESS: <%= ENV["SMTP_ADDRESS"] %>
  SMTP_USER_NAME: <%= ENV["SMTP_USER_NAME"] %>
  SMTP_PASSWORD: <%= ENV["SMTP_PASSWORD"] %>
  SMTP_DOMAIN: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_FROM: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_ERRORS_RECEIVER: <%= ENV["EMAIL_ERRORS_RECEIVER"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  SECRET_HMAC: <%= ENV["SECRET_HMAC"] %>
  SMTP_ADDRESS: <%= ENV["SMTP_ADDRESS"] %>
  SMTP_USER_NAME: <%= ENV["SMTP_USER_NAME"] %>
  SMTP_PASSWORD: <%= ENV["SMTP_PASSWORD"] %>
  SMTP_DOMAIN: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_FROM: <%= ENV["SMTP_DOMAIN"] %>
  EMAIL_ERRORS_RECEIVER: <%= ENV["EMAIL_ERRORS_RECEIVER"] %>